# Generated by Django 5.0 on 2023-12-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='defense_sp',
            new_name='special_attack',
        ),
    ]
